package FC.servlet;

import FC.Model.User;
import FC.Dao.UserDao;
import java.io.IOException;
import java.io.PrintWriter;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 * Servlet implementation for user signup
 */
@WebServlet("/SignupServlet")
public class SignUpServlet extends HttpServlet {
    private static final long serialVersionUID = 1L;

    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.setContentType("text/html;charset=UTF-8");
        try (PrintWriter out = response.getWriter()) {

            // Retrieve form parameters
            String firstName = request.getParameter("firstName");
            String lastName = request.getParameter("lastName");
            String email = request.getParameter("email");
            String gender = request.getParameter("gender");
            String nicNumber = request.getParameter("nicNumber");
            String address = request.getParameter("address");
            String phone = request.getParameter("phone");
            String password = request.getParameter("password");
            String confirmPassword = request.getParameter("confirmPassword");
            String userRole = "customer"; // Default role for new users
            String createdAt = java.time.LocalDateTime.now().toString();
            String updatedAt = createdAt;

            // Validate input (add more validation as needed)
            if (firstName == null || lastName == null || email == null || password == null || confirmPassword == null
                    || gender == null || nicNumber == null || address == null || phone == null
                    || firstName.isEmpty() || lastName.isEmpty() || email.isEmpty() || password.isEmpty()
                    || confirmPassword.isEmpty() || gender.isEmpty() || nicNumber.isEmpty() || address.isEmpty()
                    || phone.isEmpty()) {
                out.println("<h3>All mandatory fields must be filled.</h3>");
                return;
            }

            // Validate passwords match
            if (!password.equals(confirmPassword)) {
                out.println("<h3>Passwords do not match. Please try again.</h3>");
                return;
            }

            // Create a User object
            User user = new User(
                    0, // userId will be auto-generated by the database
                    firstName,
                    lastName,
                    email,
                    gender,
                    nicNumber,
                    password, // Note: Hash the password before storing it in production
                    phone,
                    address,
                    userRole,
                    createdAt,
                    updatedAt
            );

            // Save the user using UserDAO
            UserDao userDAO = new UserDao();
            boolean isSaved = userDAO.saveUser(user);

            if (isSaved) {
                out.println("<h3>User registered successfully!</h3>");
            } else {
                out.println("<h3>Failed to register user. Please try again.</h3>");
            }
        }
    }

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        response.sendRedirect("signup.jsp"); // Redirect to signup page if accessed via GET
    }
}